services:
  - type: web
    name: personal-finance-tracker
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Personal_Finance_Tracker_Web-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://switchyard.proxy.rlwy.net:36111/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: MMhfpwSyLLmTQGjvHYxeMEyXhuVGODSW
      - key: SERVER_PORT
        value: 10000
